# NumPy :-> Numerical Python

## It gives us multidimensional arrays, nd arrays

## why numpy over lists?

### 1.less memory
### 2. time execution
### 3.conveniece
### 4.functionality

### in order to add 8 elements of two arrays of size 8 numpy doesnt need to perform 8 operations

### numpy arrays contain only element of same type

In [1]:
import numpy as np
li_arr = [i for i in range(0,100)]
np_arr = np.arange(100)

print(li_arr)
print(np_arr)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [3]:
## Size comparision

print(np_arr.itemsize)
print(np_arr.itemsize * np_arr.size)

4
400


In [4]:
import numpy as np
a = [1,2,3]
b = np.array(a)
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [9]:
#numpy arrays can only contain elements of same type
import numpy as np
a = [1,2,3, 4.5]
b = np.array(a, dtype = float)
print(b)
print(type(b))

[1.  2.  3.  4.5]
<class 'numpy.ndarray'>


In [11]:
b = np.array(a*3)
print(b)

[1.  2.  3.  4.5 1.  2.  3.  4.5 1.  2.  3.  4.5]


In [19]:
b = np.ones((2,3))
c = np.zeros(3)
d = np.full(3,-1)
print(b)
print(c)
print(d)

[[1. 1. 1.]
 [1. 1. 1.]]
[0. 0. 0.]
[-1 -1 -1]


In [22]:
a = np.empty(3, dtype = int)
print(a)

[781475264       575         0]


In [23]:
a = [[1,2,3],[4,5,6],[7,8,9]]
b = np.array(a,dtype=int)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
b=np.array([int(x==4) for x in range(10)])
print(b)

[0 0 0 0 1 0 0 0 0 0]


In [34]:
c = np.arange(9,50)
print(c)

[ 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32
 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [3]:
b = np.arange(2,10)
print(b)
c = np.arange(2,10,2)
print(c)

[2 3 4 5 6 7 8 9]
[2 4 6 8]


In [31]:
b = np.random.rand(2,3)
print(b)

[[0.69366065 0.23516549 0.58495147]
 [0.52011563 0.90188677 0.90531623]]


In [32]:
b = np.random.rand(10)*10
print(b)

[2.44979202 7.50128908 5.09701644 1.06414463 0.85673352 2.07850709
 1.67151248 8.39927034 8.83736126 8.70324845]


In [33]:
np.random.rand()

0.9984836567807197

# Properties : data, shape, dtype, stride

In [41]:
import numpy as np
li = [1,2,3,4]

arr = np.array(li)

print(arr)
print(arr.data)
print(arr.shape)
print(arr.dtype)
print(arr.strides) #8 bytes are needed to be moved in order to get to next elemrnt

[1 2 3 4]
(4,)
int32
(4,)


In [46]:
li_2d = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
arr_2d = np.array(li_2d)
print(li_2d)
print(arr_2d)


print(arr_2d[2][1])
print(arr_2d[2,1])



[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
10
10


In [48]:
print(li_2d[1][:3])
print(arr_2d[1][:3])
print(arr_2d[1, :3])

[5, 6, 7]
[5 6 7]
[5 6 7]


In [50]:
print(li_2d[0:3][2])

[9, 10, 11, 12]


In [60]:
x = li_2d[0:3]
print(x)
y = x[2]
print(y)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[9, 10, 11, 12]


## NumPy is better for slicing than normal list

In [56]:
print(arr_2d[0:3][2])
print(arr_2d[0:3,2])

[ 9 10 11 12]
[ 3  7 11]


In [59]:
print(arr_2d[2: ,1:3])

[[10 11]
 [14 15]]


In [5]:
b = np.linspace(2, 10, 5, dtype = int)
print(b)

[ 2  4  6  8 10]


In [8]:
b = np.linspace(2, 10)
print(b)
print(b[1] - b[0])
print(b[3] - b[2])

[ 2.          2.16326531  2.32653061  2.48979592  2.65306122  2.81632653
  2.97959184  3.14285714  3.30612245  3.46938776  3.63265306  3.79591837
  3.95918367  4.12244898  4.28571429  4.44897959  4.6122449   4.7755102
  4.93877551  5.10204082  5.26530612  5.42857143  5.59183673  5.75510204
  5.91836735  6.08163265  6.24489796  6.40816327  6.57142857  6.73469388
  6.89795918  7.06122449  7.2244898   7.3877551   7.55102041  7.71428571
  7.87755102  8.04081633  8.20408163  8.36734694  8.53061224  8.69387755
  8.85714286  9.02040816  9.18367347  9.34693878  9.51020408  9.67346939
  9.83673469 10.        ]
0.16326530612244916
0.16326530612244916


In [13]:
b = np.linspace(2,10,5, dtype = int)
print(b)

[ 2  4  6  8 10]


In [14]:
# Identity
b = np.identity(3)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
b = np.eye(4,5)
print(b)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [29]:
b = np.random.rand(3)
print(b)

[0.95635751 0.26713712 0.03938398]


In [25]:
b = np.random.randint(100)
print(b)

32


In [32]:
b = np.random.randint(10,90,(4,5))
print(b)

[[81 85 57 53 64]
 [46 39 52 83 40]
 [21 46 22 81 54]
 [45 70 14 17 72]]


In [35]:
b = np.eye(5,6)
print(b)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]


In [40]:
b = np.linspace(0,5,10, dtype = float)
print(b)
print(b[1] - b[0])
print(b[2] - b[1])

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
0.5555555555555556
0.5555555555555556


## word file question

In [61]:
a = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]]
print(a)

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]


In [62]:
b = np.array(a)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [63]:
print(b[2:3, :3])

[[11 12 13]]


In [64]:
print(b[3, 1:])
print(b[2:,:])
print(b[1:3, 1:3])

[17 18 19 20]
[[11 12 13 14 15]
 [16 17 18 19 20]]
[[ 7  8]
 [12 13]]


# Mathematical Operations

import numpy as np
li = [1,2,3,4,5]
a =  np.random.randint(1,20,5)
b =  np.random.randint(1,20,5)

print(li)
print(a)
print(b)

In [65]:
import numpy as np 

li = [1,2,3,4,5] 
a = np.random.randint(1,20,5) 
b = np.random.randint(1,20,5)

print(li) 
print(a) 
print(b)

[1, 2, 3, 4, 5]
[18  4 18  1  3]
[ 9  4 11 16 15]


In [66]:
li = [i+1 for i in li]
print(li)

#We have to iterate over each element

[2, 3, 4, 5, 6]


In [67]:
a = a + 1
print(a)
#numpy uses vectorization

[19  5 19  2  4]


In [68]:
c = a + b
print(c)

[28  9 30 18 19]


In [69]:
d = a - b
print(d)

[ 10   1   8 -14 -11]


In [71]:
#similarly we can do / or // or * or **

print(a)
print(a.sum())
print(a.mean())
print(a.min())
print(a.argmin())
print(a.max())
print(a.argmax())

[19  5 19  2  4]
49
9.8
2
3
19
0


In [73]:
print(a)
print(b)
print(a > b)
print(a == b)

[19  5 19  2  4]
[ 9  4 11 16 15]
[ True  True  True False False]
[False False False False False]


In [74]:
print(a)
print(b)
print(np.logical_or(a,b))
print(np.logical_and(a,b))
print(np.logical_not(a,b))

[19  5 19  2  4]
[ 9  4 11 16 15]
[ True  True  True  True  True]
[ True  True  True  True  True]
[0 0 0 0 0]


## Boolean Indexing

In [75]:
import numpy as np

a = np.array(['t','b','r','d','e','f','z','e'])
b = np.random.randint(1,20,8)

print(a)
print(b)

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'e']
[12  7  3  8 15  5  2  5]


In [76]:
print(b > 10)

[ True False False False  True False False False]


In [78]:
bool_arr = b>10
print(bool_arr)
new_arr = b[bool_arr]
print(new_arr)

[ True False False False  True False False False]
[12 15]


In [79]:
new_arr = b[b>10]
print(new_arr)

[12 15]


In [80]:
c = b
c

array([12,  7,  3,  8, 15,  5,  2,  5])

In [82]:
c[:3] = 19
print(c)
c[c > 15] = 100
print(c)

[19 19 19  8 15  5  2  5]
[100 100 100   8  15   5   2   5]


In [83]:
print(b)

[100 100 100   8  15   5   2   5]


In [84]:
print(b[b==100])

[100 100 100]


In [86]:
ind = np.where(b == 100)
print(ind)

(array([0, 1, 2], dtype=int64),)


In [88]:
a = [1,2,0,0,4,0]
a = np.array(a)
ind = np.where( a != 0)
print(ind)

(array([0, 1, 4], dtype=int64),)


In [89]:
a = [1,2,3,4,5,6,7,8,9,10]
a = np.array(a)

ind = np.where(a % 2 == 1)
a[ind] = -1
print(a)

[-1  2 -1  4 -1  6 -1  8 -1 10]


# Using 2d arrays

# BroadCasting (when size of arrays are different)

In [ ]:
# if x : 2*3  and y : 3*2 then + , - will give error

In [5]:
# if one of then is one then they are compatible
# example : 3,3 and 3 (or 1,3)
x = np.random.randint(1,10,(3,3))
y = np.random.randint(1,10,(3))
print(x)
print(y)

[[3 2 1]
 [8 3 3]
 [7 8 4]]
[3 7 7]


In [6]:
ans = x - y
print(ans)

[[ 0 -5 -6]
 [ 5 -4 -4]
 [ 4  1 -3]]


In [7]:
x = np.random.randint(1,10,(3,2))
y = np.random.randint(1,10,(2, 3))
print(x)
print(y)

[[5 2]
 [6 9]
 [3 4]]
[[9 8 8]
 [8 8 4]]


In [8]:
print(x-y)

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [9]:
y = np.transpose(y)
print(y)
print(x-y)

[[9 8]
 [8 8]
 [8 4]]
[[-4 -6]
 [-2  1]
 [-5  0]]


In [10]:
#resize and reshape
gfg = np.array([1, 2, 3, 4, 5, 6]) 
print("Original array:")
display(gfg)  
  
# using reshape()
print("Changed array")
display(gfg.reshape(2, 3)) 
    
print("Original array:")
display(gfg)

Original array:


array([1, 2, 3, 4, 5, 6])

Changed array


array([[1, 2, 3],
       [4, 5, 6]])

Original array:


array([1, 2, 3, 4, 5, 6])

In [11]:

# importing the module
import numpy as np 
    
# creating an array 
gfg = np.array([1, 2, 3, 4, 5, 6]) 
print("Original array:")
display(gfg)  
  
# using resize()
print("Changed array")
# this will print nothing as None is returned
display(gfg.resize(2, 3)) 
    
print("Original array:")
display(gfg)

Original array:


array([1, 2, 3, 4, 5, 6])

Changed array


None

Original array:


array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
import numpy as np
import csv
file_obj = open('./year2017.csv')
data = csv.DictReader(file_obj, skipinitialspace = True)

killed = []
wounded = []
country = []
for row in data:
#     print(row)
      killed.append(row['Killed'])
      country.append(row['Country'])
      wounded.append(row['Wounded'])
# print(killed)
# print(wounded)
# print(country)
np_killed = np.array(killed)
np_wounded = np.array(wounded)
np_country = np.array(country)


# print(np_killed)
# print(np_wounded)
# print(np_country)

In [28]:
a = np_killed == ''
print(a)
np_killed[a]
np_killed[a] = '0.0'
print(np_killed)
# a = np_killed == ''
# print(a)

[False False False ... False False False]
[False False False ... False False False]


In [32]:
a = np_wounded == ''
print(a)
np_wounded[a]
np_wounded[a] = '0.0'

[False False False ... False False False]


In [33]:
np_killed = np.array(np_killed, dtype = float)
np_wounded = np.array(np_wounded, dtype = float)

In [34]:
killed_wounded = np_killed + np_wounded

In [35]:
print(killed_wounded)

[0. 2. 7. ... 0. 0. 0.]


In [36]:
np_country = np.array(country)

In [37]:
np_country == 'India'

array([False, False, False, ..., False,  True, False])

In [41]:
arr = killed_wounded[np_country == 'India']
ans = np.sum(arr)
ans2 = np.sum(killed_wounded)
print(ans)
print(ans2)

1157.0
48263.0


In [1]:
import pandas as pd

ModuleNotFoundError: No module named 'pandas'